# Generated by Django 6.0.5 on 2026-06-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_userprofile_name_message_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='message_history',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
