# Generated by Django 6.0.5 on 2026-07-01 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_userprofile_avg_response_time_userprofile_cache_hits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='last_active',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='message_history',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='app1.chatsession'),
        ),
    ]
