# Generated by Django 6.0.5 on 2026-07-08 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_chatsession_last_active_message_history_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='last_active',
        ),
    ]
