# Generated by Django 6.0.5 on 2026-08-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='github_username',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
