# Generated by Django 6.0.5 on 2026-08-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_resume_github_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='version',
            new_name='resume_version',
        ),
        migrations.AddField(
            model_name='resume',
            name='github_summary',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='resume_summary',
            field=models.TextField(null=True),
        ),
    ]
