# Generated by Django 6.0.5 on 2026-08-23 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_rename_version_resume_resume_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='uploaded_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
