# Generated by Django 6.0.5 on 2026-08-23 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_resume_uploaded_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='uploaded_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
